name: Block direct pushes to main
#

# Trigger on every push to branch "main"
on:
  push:
    branches:
      - main

jobs:
  cancel_direct_push:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if commit is not a merge commit from PR
        run: |
          echo -e " Direct pushes to main are prohibited.\nPlease open a pull request if this was not a mistake."
          exit 1
